### ISSUE TITLE
variant not scored

### ISSUE THREAD

**Issue by fabiennejh** [raphaelleman/SPiP#3]
Hello,

I'm trying to use SPiP, and I'm wondering why there are some variants not scored even if a transcript is found  by the software :  

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	CKD54	varID	Interpretation	InterConfident	chr	strand	gNomen	varType	ntChange	ExonInfo	transcript	gene	NearestSS	DistSS	RegType	seqPhysio	seqMutated	SPiCEproba	SPiCEinter_2thr	deltaMES	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
chr1	13656	.	CAG	C	.	.	.	.	0/0	NR_046018:g.13656_13658:delinsC	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA

Thank you for your help !
Fabienne

**Comment by raphaelleman** [comment]
Hello,

Thank you for you interest for SPiP.

Your issue is strange because when SPiP runs your example, the variant is scored. 
Input: 
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	
chr1	13656	.	CAG	C	.	.	. `

Output:
`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	varID	Interpretation	InterConfident	chr	strand	gNomen	varType	ntChange	ExonInfo	transcript	gene	NearestSS	DistSS	RegType	seqPhysio	seqMutated	SPiCEproba	SPiCEinter_2thr	deltaMES	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
chr1	13656	.	CAG	C	.	.	.	NR_046018:g.13656_13658:delinsC	NTR	01.24 % [00.71 % ; 02.15 %]	chr1	+	13656;13658	delins	delinsC	Exon 3 (1189)	NR_046018	DDX11L1	acceptor	436; 438	Exon	[...] `

CMD:
`Rscript /path/to/SPiPv1.0.r --input /path/to/input.vcf --output /path/to/output.txt --SamPath /path/to/samtools --fastaGenome /path/to/hg19.fa --GenomeAssenbly hg19 --threads 1 --maxLines 1000`

Could you precise the command line of SPiP used and if you have some error during the analysis.

Regards

**Comment by fabiennejh** [comment]
Thank you for your answer.
In fact, my path towards samtools was corrupted, so it explains the problem. Now it works better.
Thank you
